function [varargout] = calcXCH_TimeWindow (times1,times2, TimeWindow,Tbin)

% plots the XCH given data read in from a txt file generated by Tints
Trange = TimeWindow;
% Tbin = 20;
nbinsA = ceil(times1(end)); % 1ms bins
hist_spikesA = hist(times1, 0.5:1:nbinsA-0.5);
nbinsB = ceil(times2(end)); % 1ms bins
hist_spikesB = hist(times2, 0.5:1:nbinsB-0.5);
crosscorr = xcorr(hist_spikesA,hist_spikesB,Trange);
if Tbin ~= 1
    crosscorr(Trange + 1) = [];
    maxbin = ceil(length(crosscorr)/Tbin);
    subs = repmat(1:maxbin,Tbin,1);
    [i,j] = size(subs);
    subs = reshape(subs,i*j,1);
    subs = subs(1:length(crosscorr));
    crosscorr = accumarray(subs,crosscorr)';
    newlags = floor(Trange/Tbin);
    crosscorr = [crosscorr(1:newlags) 0 crosscorr(newlags+1:end)];
end
y = -Trange:Tbin:Trange;
crosscorr(crosscorr<0.5) = 0;% removes minute values that are basically 0
crosscorr(crosscorr>0.5 & crosscorr<1) = 1; % catches 0.99r values
varargout{1} = crosscorr;
varargout{2} = y;
end